apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flask2
  template:
    metadata:
      labels:
        app: hello-flask2
    spec:
      containers:
      - name: hello-flask2
        image: waseemrizi/hello-flask-app2:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-flask2-service
spec:
  type: NodePort
  selector:
    app: hello-flask2
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002
